spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create  # or 'update' if you want to keep existing data
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public  # Specify your default schema here
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    sql:
      init:
        mode: always  # Ensure data.sql is executed

application:
  mailing:
    frontend:
      activation-url: http://localhost:4201/activate-account

file:
  uploads:
    photos-output-path: ./uploads

server:
  port: 8080
